#!/bin/python

import sys
import os

def main(argv):
    tb_name = argv[1]
    is_dc_bed = tb_name.find("dcdev")
    login_cmd = "sshpass -p tigris ssh -o StrictHostKeyChecking=no mv" + tb_name + "@mv" + tb_name
    if is_dc_bed < 0:
        login_cmd += ".mv.nuagenetworks.net"

    print login_cmd
    print " "
    os.system(login_cmd)

if __name__ == '__main__' :
    try :
        main (sys.argv)
    except SystemExit :
        # Let system.exit() calls complete normally
        raise
